build: off


install:
  - ps: Install-Product node 8
  - git submodule update --init --recursive
  - yarn install
  - yarn install-plugins
  - yarn ci:compile

test_script:
  - yarn screentest
  - 7z a screentest.zip test-dist\screentest\*
  - ps: $env:warning_ico = ":warning:"
  - ps: $env:success_ico = ":white_check_mark:"
  - ps: $env:changed_screens = (Get-Content -Raw -Path test-dist\screentest\state.json | ConvertFrom-Json).changedScreens
  - ps: If ($env:changed_screens -gt 0) {Add-AppveyorMessage $env:warning_ico $env:changed_screens screens have been changed"} else { Add-AppveyorMessage $env:success_ico no screens changed" }

artifacts:
  - path: 'screentest.zip'
    name: Screentests

notifications:
  - provider: GitHubPullRequest
    template: "{{#fail}}:x: build failed{{/fail}} {{#jobs}} {{#messages}} {{message}} {{/messages}} {{/jobs}}"
