trigger:
- staging

pool:
  name: 'Default'

steps:

- bash: yarn install --frozen-lockfile --check-files
  displayName: 'Install Dependencies'

- bash: 'yarn lint'
  displayName: 'TSLint'

- bash: 'yarn compile:ci'
  displayName: 'Compile Assets'

- bash: 'yarn test-flaky --match="Main and child window visibility"'
  displayName: 'Run Tests'
  env:
    SLOBS_TEST_USER_POOL_TOKEN: $(userPoolToken)
    CI: true
    BROWSER_SOURCE_HARDWARE_ACCELERATION: 'OFF'
    SLOBS_TEST_STREAM_KEY: $(twitchStreamKey)
