trigger:
- azure

pool:
  name: 'Default'

steps:

- script: yarn install --frozen-lockfile --check-files
  displayName: 'Install Dependencies'

- script: 'yarn lint'
  displayName: 'TSLint'

- script: 'yarn compile:ci'
  displayName: 'Compile Assets'

- script: 'yarn test-flaky'
  displayName: 'Run Tests'
  env:
    SLOBS_TEST_USER_POOL_TOKEN: $(userPoolToken)
    CI: true
    BROWSER_SOURCE_HARDWARE_ACCELERATION: 'OFF'
    SLOBS_TEST_STREAM_KEY: $(twitchStreamKey)
