trigger:
  - staging
  - master

variables:
  CI: true
  TEMP_DIR: $(Build.SourcesDirectory)/temp

jobs:
  - job: Test
    pool:
      name: 'Default'

    workspace:
      clean: resources

    strategy:
      parallel: 4

    steps:
      # Step to create temp directory and set TEMP & TMP environment variables on Windows
      - powershell: |
          New-Item -ItemType Directory -Force -Path $(TEMP_DIR)
          echo "##vso[task.setvariable variable=TEMP]$(TEMP_DIR)"
          echo "##vso[task.setvariable variable=TMP]$(TEMP_DIR)"
        displayName: 'Set TEMP and TMP environment variables'

      - powershell: echo "IP for RDP connections:" $(Invoke-RestMethod ipinfo.io/ip)
        displayName: 'Get RDP address'

      - powershell: Set-DisplayResolution -Width 1920 -Height 1080 -Force
        displayName: 'Setup Screen Resolution'

      - script: yarn install --immutable 2>&1
        displayName: 'Install Dependencies'

      - script: node node_modules/electron/install.js
        displayName: 'Install Electron'

      - script: 'yarn ci:compile'
        displayName: 'Compile Assets'

      - script: 'yarn ci:tests'
        displayName: 'Run Tests'
        env:
          SLOBS_TEST_USER_POOL_TOKEN: $(userPoolToken)
          BROWSER_SOURCE_HARDWARE_ACCELERATION: 'OFF'
          SLOBS_TEST_STREAM_KEY: $(twitchStreamKey)
          SLOBS_TEST_RUN_CHUNK: "$(System.JobPositionInPhase)/$(System.TotalJobsInPhase)"
      - publish: $(Build.SourcesDirectory)/
        displayName: 'Publish Build Artifacts on Test Failure'
        condition: failed()
        artifact: failed-test-build-$(Build.BuildId)

  - job: Check_eslint_and_strict_nulls_regression

    pool:
      name: 'Default'

    workspace:
      clean: resources

    steps:

      - powershell: echo "IP for RDP connections:" $(Invoke-RestMethod ipinfo.io/ip)
        displayName: 'Get RDP address'

      - powershell: Set-DisplayResolution -Width 1920 -Height 1080 -Force
        displayName: 'Setup Screen Resolution'

      - script: yarn install --immutable 2>&1
        displayName: 'Install Dependencies'

      - script: 'yarn eslint'
        displayName: 'ESLint'

      - script: 'yarn compile:strictnulls'
        displayName: 'Check regressions in files with strictNullChecks'

  - job: macOS

    pool:
      vmImage: macOS-latest

    workspace:
      clean: resources

    steps:
      - script: yarn install --immutable --network-timeout 1000000 2>&1
        displayName: 'Install Dependencies'

      - script: node node_modules/electron/install.js
        displayName: 'Install Electron'

      - script: 'yarn eslint'
        displayName: 'ESLint'

      - script: 'yarn ci:compile'
        displayName: 'Compile Assets'
